$(document).ready(function(){
  $("#username").click(function(){
        }).keyup(function(){
        $.post("content.php",{username:$("#username").val()},function(data){
               $("#id1").text(data);
               });
    }).blur(function(){
        $("#id1").text("");
    });
});